### ISSUE TITLE
PlantUML not working

### ISSUE THREAD

**Issue by mnlipp** [codimd/container#102]
I have "started" CodiMD using the distributed docker-compose.yml. In general, it works. However, PlantUML source is not processed. The plantuml source is simply handled as a code block with some words highlighted in red.

Am I doing something wrong or is this a (configuration) bug?

**Comment by SISheogorath** [comment]
Well, this is due to the fact that CodiMD doesn't support PlatnUML yet: https://github.com/codimd/server/pull/29

Most likely you came across this feature in the hackmd-codimd version, which isn't involved here.

**Comment by mnlipp** [comment]
Okay, thanks. I've read the history section, but it isn't easy to sort things out.
