### ISSUE TITLE
404 with a reverse proxy

### ISSUE THREAD

**Issue by icolab** [codimd/container#110]
Hi, 
I did an install of CodiMD using the docker-container. 
Over the port 3000 Codi is working well. I set up a reverse proxy using nginx in order to use my custom domain name and to access codi at mydomain/pad
I use the https://hackmd.io/c/codimd-documentation/%2F%40codimd%2Fweb-server-nginx for my configuration 
On the docker-compose.yml, I add:
      - CMD_URL_PATH=pad
      - CMD_DOMAIN=mydomain
      - CMD_PROTOCOL_USESSL=true
I let also - "3000:3000"
However, when I go to mydomain/pad, I got a 404 not found and the links a referring to https://mydomain:3000/pad/new instead of https://mydomain/pad/new

Sincerely

**Comment by ErikMichelson** [comment]
Hi,

first of all: The hackmd.io-version of CodiMD is different from our version, therefore the documentation you've linked is not the correct one. Our documentation resides in the [`/docs` directory of the project](https://github.com/codimd/server/tree/HEAD/docs). 

Regarding your problem: You need to set the environment variable [`CMD_URL_ADDPORT=false`](https://github.com/codimd/server/blob/HEAD/docs/configuration.md#codimd-location) to stop CodiMD from appending the port number to your domain name.

If you have any further questions related to this, feel free to ask. :)

**Comment by icolab** [comment]
Thanks for your answer. I do use this container, I just also use their documentation for some details. I will be more carefully regarding the doc.

I did it for the port, it's better but I still have this strange behaviour where a page is loading (with no css or js) but remains the 404 not found oops (you can see it online at https://icolab.fr/pad

**Comment by SISheogorath** [comment]
Seems like your reverse-proxy doesn't send out the proper mime-types or generally seems misconfigured. can you check what URLs show up in your CodiMD logs?

**Comment by ErikMichelson** [comment]
That looks like a problem with your nginx config. Be sure to include tha trailing slash in the `proxy_pass` command.

The following minimal config is working for me:
![image](https://user-images.githubusercontent.com/52606896/86632377-9ceaf200-bfcf-11ea-8608-8d452a90b734.png)

If I omit the trailing slash in the `proxy_pass` directive, I get the same error as yours.

**Comment by icolab** [comment]
It was the trailing slash .... thanks a lot !
Now I have to understand why the GET | https://icolab.fr/pad/new gives 404 Not Found or the login (Cannot POST //login)

**Comment by icolab** [comment]
In fact, the config file is not loading when I arrived on the webpage (neither the me)

**Comment by icolab** [comment]
any idea @ErikMichelson? 
In nginx's error log, I only have `2020/07/20 17:51:54 [error] 1279363#1279363: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 46.193.66.171, server: icolab.fr, request: "POST /pad/login HTTP/2.0", upstream: "http://127.0.0.1:3000//login`

But when I went to others pages with a 404 not found, I have nothing neither in nginx log or in codimd debug

**Comment by ErikMichelson** [comment]
I'm sorry, but I don't know a solution for that problem.

CodiMD/HedgeDoc is mostly used with a separate subdomain, and we mainly focus on separate subdomains while developing. I therefore can imagine that it might also be a problem inside our code.

**Comment by ErikMichelson** [comment]
Well, there is one thing you maybe want to test out:

Use the config as I posted above but change the following:
- `location /pad {` to `location /pad/ {` (trailing slash here)
- add inside the location block `proxy_redirect off;`

I did start a test-server in a subfolder [here](https://codimd-2.test.fsbremen.de/pad/features). While I just had a quick look at it, at least it seems to show the features page as well as the main page successfully.

**Comment by icolab** [comment]
You were rigth, the trailing slash was also missing... 
Thanks a lot for your help, everything is fine now!

**Comment by knoxell** [comment]
For anyone having this problem with **apache** I changed the location from `/pad` to `/pad/` (in the hedgedoc specific conf file) as suggested above and it worked as well.

If you're still having problems or want the pad reachable via /pad you can add
```apacheconf
RewriteEngine on 
RewriteRule ^/pad$ /pad/ [R]
```
in front of your other HedgeDoc related configurations.

cheers!
