### ISSUE TITLE
Switch to package repository for gosu

### ISSUE THREAD

**Issue by SuperSandro2000** [codimd/container#116]
Gosu is both in [Alpine](https://pkgs.alpinelinux.org/package/edge/testing/x86_64/gosu) and [Debian](https://packages.debian.org/buster/gosu). I think it would be less maintenance work and would reduce the image complexity by a bit if we start to use them. Thoughts?

**Comment by SISheogorath** [comment]
I think it would be a perfect way to start hacktoberfest
