### ISSUE TITLE
ERROR: manifest for quay.io/codimd/server:1.3.1 not found

### ISSUE THREAD

**Issue by MelBourbon** [codimd/container#27]
When pulling new docker after git-pull to update to 1.3.1 I receive the following error message
```
Pulling app (quay.io/codimd/server:1.3.1)...
ERROR: manifest for quay.io/codimd/server:1.3.1 not found
```

**Comment by SISheogorath** [comment]
Yes, it's on its way, sadly TravisCI decided to have a bad day this evening.

Also, please retry, one of the builds just made it: https://quay.io/repository/codimd/server?tab=tags

Guess it's just a timing problem, should be solved :)

**Comment by MelBourbon** [comment]
Yeah, was timing. It's resolved :-) Sorry and thanks.
