### ISSUE TITLE
How can I hardcode new passwords in the DB somehow 

### ISSUE THREAD

**Issue by CynthiaChuang** [codimd/container#34]
Sorry , I think it is a stupid problem.  But how can I hardcode new passwords in the DB somehow for user?

According to the answer to [this question](https://github.com/hackmdio/codimd/issues/434), I can change the DB.  But I have no idea where the db is... I can't find any db in /var/lib/docker/volumes/codimd-container_database...

**Comment by SISheogorath** [comment]
Oh the good new is, we have you covered and you don't need to access the DB directly, the bad news is, we have no beautiful GUI for it.

Run `docker-compose exec codimd ./bin/manage_users --reset <mail address>` and you should be prompted for the new password of the user.

When you use any external authentication method (ldap, saml, github, gitlab, …) you have to use their password reset procedure.

**Comment by marcbria** [comment]
Notice email address is case sensitive.
