### ISSUE TITLE
codimd how to enable invitee on container 

### ISSUE THREAD

**Issue by Linusshen** [codimd/container#37]
how to enable invitee on codimd ? 
CodiMD Configuration not write how to enable invitee
or now codimd not support invitee? 
thanks

**Comment by SISheogorath** [comment]
I'm not completely sure what you mean by invitee. If you are talking about a feature where CodiMD sends out an email with a unique link, no, we don't support that.

**Comment by Linusshen** [comment]
thank you your answer , I just mean sends out an email with a unique link.
