### ISSUE TITLE
Use as component in Vue ？

### ISSUE THREAD

**Issue by TianPuJun** [codimd/container#88]
Use as component in Vue ？

**Comment by TianPuJun** [comment]
I want to use it in the Vue project. Can I use NPM install to install it in the Vue project, and edit the file by entering the URL of the MD file

**Comment by SISheogorath** [comment]
This can't work. This project, CodiMD container is for the CodiMD [OCI container](https://www.opencontainers.org/) and has nothing to do with vue. It's currently only possible to embed CodiMD using iframes. But not for editing external files, as you noted in https://github.com/codimd/server/issues/310.

**Comment by TianPuJun** [comment]
ok 3ku
