### ISSUE TITLE
Backup and Restore CodiMD Container(s)

### ISSUE THREAD

**Issue by elearningdienst** [codimd/container#98]
I can't find a documentation how to backup and restore respectively migrate a working (dockerized) codimd installation to a new server. There should be a short documentation about that toppic.

If anyone have Ideas how to do that I'm willing to try oud and do that documentation for all. I have the need to migrate to another server.

**Comment by ErikMichelson** [comment]
This reply is not a fully backup and restore guide, but just giving some hints.
Depending on your chosen image upload solution there are multiple things to backup. 

- The most important one is the database. The provided `docker-compose.yml` uses a postgres database that can be dumped into a backup file with the `pg_dump` utility. For restoring the dump file, you may call something like `psql -d hackmd -f backupfile.sql` inside the new database container. The _hackmd_ in the command is the name of the database, just in case you changed it.

- If you're sticking with the defaults, uploaded images will be stored on imgur, so there's no need to back them up while migrating to another server. But if you've changed it to 'filesystem', be sure to back them up too. When using internal docker volumes, you'll usually find the data in `/var/lib/docker/volumes`.
 
- Finally, copy your configuration (probably the `docker-compose.yml` with environment variables) to your new server.

**Comment by SISheogorath** [comment]
@elearningdienst don't run the container with any additional volumes, the database is the only content that has to be backed up and migrated. The CodiMD container itself is designed to be stateless (if you don't use filesystem as upload storage) and therefore can be started on any machine without the need of migrations.

The database itself has of course to be migrated as it contains your user data. This is described in the README: https://github.com/codimd/container#backup

Basically as @ErikMichelson described: Make a database dump, copy the dump and the compose file over, start the database, restore the dump and start codimd itself.

```sh
oldsrv# docker-compose stop app
oldsrv# docker-compose rm app
oldsrv# docker-compose exec database pg_dump hackmd -U hackmd  > backup.sql
oldsrv# scp docker-compose.yml backup.sql user@newsrv:/path/to/codimd
newsrv# cd /path/to/codimd
newsrv# docker-compose up -d database
newsrv# cat backup.sql | docker exec -i $(docker-compose ps -q database) psql -U hackmd
newsrv# docker-compose up -d
```

This would be the step **without additional volumes**. If you defined a volume for images or alike, you need to add additional steps to restore those volumes.

**Comment by elearningdienst** [comment]
Its that easy. Thank you!
